# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
 repositories:
   - repository: manifests
     type: github
     endpoint: TejaGithub
     name: ramakrishnateja/gitops-sample-app-config
     ref: deploy


pool:
  vmImage: ubuntu-latest

steps:
- checkout: manifests
  persistCredentials: true

- script: |
    git config user.email "azdevops@gitops.com"
    git config user.name "azdevops gitops"
    cd dev
    echo $(Build.BuildNumber) > log.txt
    cd ../
    git add *
    git commit -m "test"
    git push origin HEAD:deploy
  displayName: 'Run a multi-line script'
