name: $(Date:yyyy.MM.dd)-gitops-app-sample-$(Build.BuildId)

variables:
  service

resources:
  repositories:
    - repository: manifests
      type: githubenterprise
      name: pwclabs/gitops-manifests
      endpoint: PwcLabsGitHubServiceConnection

trigger:
  branches:
    include:
      - master
      - feature/*
  paths:
    exclude:
      - azure-pipelines.yml
      - variables.yml

pool: Gitops-Build-Agents

stages:
  - stage: prebuild
    displayName: 'Pre Build'
    jobs:
      - job: 