stages:
- stage: Build
  dependsOn: PreBuild
  displayName: Build
  jobs:
  - job: Build
    steps:
      - script: |
          echo "Unit testing"
        displayName: "Unit Testing"

      - script: |
          echo "Code Coverage"
        displayName: "Code Coverage"