parameters:
  - name: RegistryServiceConnection
    type: string

  - name: ImageName
    type: string

stages:
  - template: ./prebuild.yml

  - template: ./build.yml

  - template: ./docker-build.yml
    parameters:
      RegistryServiceConnection: ${{ parameters.RegistryServiceConnection }}
      ImageName: ${{ parameters.ImageName }}
