parameters:
  - name: RegistryServiceConnection
    type: string

  - name: ImageName
    type: string

stages:
  - template: ./prebuild.yml
    displayName: Prebuild

  - template: ./build.yml
    displayName: Build

  - template: ./docker-build.yml
    displayName: Docker Build
    parameters:
      RegistryServiceConnection: ${{ parameters.RegistryServiceConnection }}
      ImageName: ${{ parameters.ImageName }}
