parameters:
- name: GitUserEmail
  type: string
- name: KustomizeImageName
  type: string
- name: ContainerIamgeName
  type: string
  
- name: Stages
  type: object
  default:
    - name: Dev
      branchName: Dev
      containerRegistryName: 'pulllogictejacontainerregistry'
      containerRegistryServiceConnectionName: 'pulllogictejacontainerregistry'
      gitopsEnvironmentPath: 'dev'
      previousStage: ''
      previousStageContainerRegistryName: ''
      previousStageContainerRegistryServiceConnectionName: ''
      devopsEnvironmentName: 'Dev'

stages:
- ${{ each deploymentStage in parameters.Stages }}:
    - stage: promote${{ lower(deploymentStage.name) }}
      displayName: Promote ${{ deploymentStage.Name }}
      ${{ if eq(parameters.previousStage, '') }}:
        dependsOn: DockerBuild
      ${{ if ne(parameters.previousStage, '') }}:
        dependsOn: promote${{ lower(deploymentStage.name) }}
      jobs:
        - deployment: Promote
          environment: ${{ deploymentStage.devopsEnvironmentName }}
          displayName: Promote
          steps:
          - ${{ if ne(parameters.previousStage, '') }}:
            - template: ./container-promote.yml
              parameters:
              ToRegistryServiceConnection: ${{ deploymentStage.containerRegistryServiceConnectionName }}
              FromRegistryServiceConnection: ${{ deploymentStage.previousStageContainerRegistryServiceConnectionName }}
              FromRegistry: ${{ deploymentStage.previousStageContainerRegistryName }}
              ToRegistry: ${{ deploymentStage.containerRegistryName }}
              ImageName: ${{ parameters.ContainerImageName }}

          - template: ./update-manifests.yml
            parameters:
              Environment: ${{ deploymentStage.gitopsEnvironmentPath }}
              GitUserEmail: ${{ parameters.GitUserEmail }}
              KustomizeImageName: ${{ parameters.KustomizeImageName }}
              ContainerRegistryName: ${{ deploymentStage.containerRegistryName }}
              ContainerImageName: ${{ parameters.ContainerImageName }}
            

            
