name: Build

on:
  workflow_call: {}

jobs:
  build:
    name: Build
    permissions:
      contents: read
      security-events: write
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Unit test
        run: |
          echo "Hello Unit Testing!"

      - name: Code coverage
        run: |
          echo "Hello Code coverage"