name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  pre-build:
    name: PreBuild
    uses: ./.github/workflows/prebuild.yml
    permissions:
      contents: read
      security-events: write

  build:
    permissions:
      contents: read
      security-events: write
    name: Build
    needs: pre-build
    uses: ./.github/workflows/build.yml

  docker-build:
    permissions:
      contents: read
      security-events: write
    name: Docker Build, Scan, Push
    needs: build
    uses: ./.github/workflows/docker-build.yml
    with:
      Docker_Organization_Name: 'docker.io/ramakrishnateja'
      Application_Name: 'gitops-app-sample'
    secrets: inherit

  gitops-dev:
    permissions:
      contents: read
      security-events: write
    name: Update Dev
    needs: docker-build
    uses: ./.github/workflows/gitops.yml
    with:
      config-repository-github-url: "github.com"
      config-repository-github-org: "ramakrishnateja"
      config-repository-name: "gitops-sample-app-config"
      environment: "dev"
      kustomize-image-name: "gitops-sample-app"
      docker-image: docker.io/ramakrishnateja/gitops-sample-app
    secrets:
      git-username: ${{ secrets.GITOPS_GIT_USERNAME }}
      git-user-email: ${{ secrets.GITOPS_GIT_USER_EMAIL }}
      git-user-pat: ${{ secrets.GITOPS_GIT_USER_PAT }}

  gitops-qa:
    permissions:
      contents: read
      security-events: write
    name: Update QA
    needs: gitops-dev
    uses: ./.github/workflows/gitops.yml
    with:
      config-repository-github-url: "github.com"
      config-repository-github-org: "ramakrishnateja"
      config-repository-name: "gitops-sample-app-config"
      environment: "qa"
      kustomize-image-name: "gitops-sample-app"
      docker-image: docker.io/ramakrishnateja/gitops-sample-app
    secrets:
      git-username: ${{ secrets.GITOPS_GIT_USERNAME }}
      git-user-email: ${{ secrets.GITOPS_GIT_USER_EMAIL }}
      git-user-pat: ${{ secrets.GITOPS_GIT_USER_PAT }}

      
    