name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  pre-build:
    name: PreBuild
    uses: ./.github/workflows/prebuild.yml@main
    permissions:
      contents: read
      security-events: write

  build:
    permissions:
      contents: read
      security-events: write
    name: Build
    needs: pre-build
    uses: ./.github/workflows/build.yml@main

  docker-build:
    permissions:
      contents: read
      security-events: write
    name: Docker Build, Scan, Push
    needs: build
    uses: ./.github/workflows/docker-build.yml@main
    with:
      Docker_Organization_Name: 'docker.io/ramakrishnateja'
      Application_Name: 'gitops-app-sample'
    