name: DockerBuild

on:
  workflow_call:
    inputs:
      Docker_Organization_Name:
        type: "string"
        required: true
      Application_Name:
        type: "string"
        required: true

jobs:
  docker:
    name: Docker Build, Scan, Push
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_ACCESS_TOKEN }}
      
      - name: Build an image from Dockerfile
        run: |
          docker build -t ${{ inputs.Docker_Organization_Name }}/${{ inputs.Application_Name }}:${{ github.sha }} .

      - name: Trivy Container scan
        run: |
          echo "Running Trivy container scanning"

      #- name: Trivy Container Scan
      #  uses: aquasecurity/trivy-action@0.2.2
      #  with:
      #    image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
      #    format: 'template'
      #    template: '@/contrib/sarif.tpl'
      #    output: 'trivy-results.sarif'
      #    severity: 'CRITICAL,HIGH'

      #- name: Upload Trivy scan results to GitHub Security tab
      #  uses: github/codeql-action/upload-sarif@v2
      #  with:
      #    sarif_file: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        run: |
          echo "Uploading Trivy scan results to Github security tab"

      - name: Push Container image
        run: |
          echo "----- Pushing image to private registry -----"