name: GitOps-CI

on:
  workflow_call:
    inputs:
      config-repository-github-url:
        description: "The github url of the config repository"
        type: "string"
        required: true
      config-repository-github-org:
        description: "The github organization name of the config repository"
        type: "string"
        required: true
      config-repository-name:
        description: "The name of the config repository"
        type: "string"
        required: true
      environment:
        description: "The name of the environment"
        type: "string"
        required: true
      kustomize-image-name:
        description: "Image name in kustomize file to be updated"
        type: "string"
        required: true
      docker-image:
        description: "docker image name"
        type: "string"
        required: true
    secrets:
      git-username:
        description: "Username of the git user to use"
        required: true
      git-user-email:
        description: "Email address of the git user to use for gitops"
        required: true
      git-user-pat:
        description: "personal access token of the gitops user"
        required: true


jobs:
  promote-dev:
    name: PromoteDev
    permissions:
      contents: read
      security-events: write
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        run: |
          git config --global user.email "${{ secrets.git-user-email }}"
          git config --global user.name "${{ secrets.git-username }}"
          git clone https://${{ secrets.git-username }}:${{ secrets.git-user-pat }}@${{ inputs.config-repository-github-url }}/${{ inputs.config-repository-github-org }}/${{ inputs.config-repository-name }}.git
          cd ${{ inputs.config-repository-name }}/${{ inputs.environment }}
          kustomize edit set image ${{ inputs.kustomize-image-name }}=${{ inputs.docker-image }}:${{ github.sha }}
          git add .
          git commit -m "Gitops Image change for ${{ inputs.environment }} with ${{ inputs.docker-image }}:${{ github.sha }}"
          git push -u origin +master
      