name: PromoteImage

on:
  workflow_call:
    inputs:
      from-repository:
        description: "The docker image repository from which the image needs to be promoted"
        type: "string"
        required: true
      to-repository:
        description: "The docker image repository to which the image is promoted to"
        type: "string"
        required: true

jobs:
  docker:
    name: Docker pull, retag and push
    runs-on: "ubuntu-latest"
    steps:
      - name: Login to From Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY}}
          password: ${{ secrets.DOCKER_REGISTRY_ACCESS_TOKEN }}
  
    